---
- name: Configure ufw rules for primary_ansible and secondary_ansible
  ufw: rule={{ item.rule }} port={{ item.port }}
  with_items:
    - { rule: 'allow', port: '22' }
    - { rule: 'allow', port: '5432'}

- name: Enable ufw
  ufw: state=enabled
