---
- name: Configure ufw rules for api_ansible
  ufw: rule={{ item.rule }} port={{ item.port }}
  with_items:
    - { rule: 'allow', port: '22' }
    - { rule: 'allow', port: '8080'}
  notify:
    - restart ufw

- name: Enable ufw
  ufw: state=enabled
