---
- name: Creates work directory
  file:
    path: /root/Geocitizen
    state: directory
    
- name: Clone a Geocitizen repository from GitHub into /Geocitizen.
  git:
    repo: git@github.com:OleksandrBoshko/Geocitizen.git
    version: master
    dest: /root/Geocitizen
    accept_hostkey: yes
  # ssh-agent doesn't allow key to pass through remote sudo commands.
  become: no
  
- name: Maven build
  shell: mvn clean install chdir=/root/Geocitizen/

- name: Copy war file to tomcat/webapp
  copy: src=target/citizen.war dest=/root 
  
- name: Restart tomcat
  service: name=tomcat state=restarted enabled=yes
