---
- name: Set up api_ansible
  hosts: api
  remote_user: root 
  become: true

  roles:
#    - apt-get-update
#    - ansible-java8-oracle
#    - tomcat9
#    - maven
#    - postgreSQL
#    - pgpool2
    - deployment
